#! /bin/bash

#configuration file name (full path)
conffile='~/www-backup/config/wwb-config.conf'
echo "   (                                  "
echo "   )\   (      )          )   (  (    "
echo "((((_)( )(  ( /(  (    ( /(  ))\ )(   "
echo " )\ _ )(()\ )(_)) )\ ) )(_))/((_(()\  "
echo " (_)_\(_((_((_)_ _(_/(((_)_(_))( ((_) "
echo "  / _ \| '_/ _` | ' \)/ _` | || | '_| "
echo " /_/ \_|_| \__,_|_||_|\__,_|\_,_|_|   "
echo "Aranaur's www-backup installation script."
echo "Find other projects at http://drewgates.com"
echo "-----------------------------------------"
echo "This script will walk you through installation of www-backup"
read -p "Press [Enter] key to start backup..."
clear

#INSTALL DEPENDENCIES

#Create bin directory
mkdir ~/www-backup
mkdir ~/www-backup/config/
echo "#! /bin/bash" > $conffile
echo "#USER CONFIGURATION. FILL OUT FIELDS AS NECESSARY. BE CAREFUL." >> $conffile
echo "###-------START-CONFIGURATION-----------------------------------------###" >> $conffile

echo "#Backup File Prefix (e.g. the 'backup' of backup20141104.tar.gz)" >> $conffile

#Create CONFIG FILE:
echo "Let's set up your config file."
echo "Your configuration can be changed at any time"
echo "and is located in ~/www-backup/config/wwb-config"
echo ""
echo ""
echo "Your Backup file prefix will prepend the date information on your archive file."
echo "(e.g. the 'backup' of backup20141104.tar.gz)"
echo "Using 'www-backup' (no quotes) is recommended."
read -p "Enter your backup file prefix" backupfp
echo "backupfp='$myname'" >> $conffile
echo "sqlfp='$myname'" >> $conffile
clear

echo "Now for your MySQL information."
echo "If you want to dump all databases, enter '--all-databases' as database name."
read -p "Enter your database name" dbname
echo "database='$dbname'" >> $conffile
read -p "Enter your database username. DO NOT USE 'root'!" dbu
echo "dbuser='$dbu'" >> $conffile
read -p "Enter your database password:" pass
echo "pass='$pass'" >> $conffile
echo "#MYSQL ROOT override: allow mysql to be exported using root account --NOT RECOMMENDED)" >> $conffile
echo "#Enter only yes or no." >> $conffile
echo "rootoverride='no'" >> $conffile

echo "#Checksums (SHA256):" >> $conffile
echo "#Local log file:" >> $conffile
shalog='~/sum.log'
echo "#Destination email:" >> $conffile
email='someone@example.com'

clear
echo "######------------############-------------######"
echo "                 Email Contacts"
echo "######------------############-------------######"
echo ""
echo "The next few settings will have no effect unless you properly installed exim4."
echo "It is reccomended that you check test exim4 configuration after this script completes."
echo "A command to test exim configuration is being stored in ~/TESTEXIM.txt"
echo ""
echo ""



echo "#Contacts:" >> $conffile
echo "#Primary Notification contact:" >> $conffile
echo "Enter an email address as your primary contact for daily backup notifications:"
read -p "Email: 
admin='king@england.com'
echo "#Secondary Notification contact:" >> $conffile
2dry='prez@thewhiteho.us'

echo "#Remote Server IP/FQDN" >> $conffile
read -p "Enter the IP or Domain of backup server:" fqdn
echo "ip='$fqdn'" >> $conffile
echo "#Remote Backup Directory (NO TRAILING "/")" >> $conffile
read -p "Enter the remote backup folder path on remote server (NO TRAILING "/". ex. /home/test/backups) bacd
echo "bd='$bacd'" >> $conffile
echo "#Remote Server Username (I created an account called 'backups', do whatever you want)" >> $conffile
read -p "Remote server username (I created an account called 'backups', do whatever you want)" susr
echo "rsuser='$susr'" >> $conffile

echo "###--------END-CONFIGURATION------------------------------------------###

#Checksum config file. If it matches the original generic file, fail script with warning to fill it out first.

#installs scripts to directory /usr/bin or ~/www-backups

#Asks if RSA key exchange is working.
#If not
#--prompts for RSA key name (or uses id_rsa if none)
#--ssh-copy-id to backup server
#--user will have to enter password at prompt.

#adds cron jobs

#######-------CREDITS-------#######
clear
echo "This script and program created by Aranaur (Drew Gates) for CGAMWR.com"
echo "  ______                       _______       __                                      
echo " |   _  \ .----.-----.--.--.--|   _   .---.-|  |_.-----.-----.  .----.-----.--------.
echo " |.  |   \|   _|  -__|  |  |  |.  |___|  _  |   _|  -__|__ --|__|  __|  _  |        |
echo " |.  |    |__| |_____|________|.  |   |___._|____|_____|_____|__|____|_____|__|__|__|
echo " |:  1    /                   |:  1   |                                              
echo " |::.. . /                    |::.. . |                                              
echo " `------'                     `-------'                                              
echo ""
read -p "Press [Enter] to finish."
clear
echo "Installation complete."

#####--------END CREDITS-----------###########
#####--------END SCRIPT------------###########
